// This files gets overwritten by docker environment variables in nginx_start.sh on docker container start
window.portalGlobal = {
  customGeofenceEnabled: true,
  disableSSO: true,
  dummyLocationShipmentsData: false,
  equipmentIdentifiersEditingEnabled: true,
  gaId: 'test-id',
  gtmId: 'test-id',
  enableGTM: false,
  locationProfileKpiCharts: true,
  locationsV2Enabled: true,
  pendoApiKey: false,
  sentryKey: 'ceed1bfebb694e8386b55664e441c411',
  sentryProject: '1492816',
  railEnabled: true,
  oceanOnModeAgnosticPage: true,
  multiValueSearchEnabled: true,
  disableAutomatedTestAccountsOnLandingMap: true,
  temperatureMonitoringV2: true,
  parcelSMSNotificationsEnabled: true,
  enableShipmentTrackingMethod: true,
  tdxEndpoint: 'https://nmc-na12.api.qa-integration.p-44.com/',
  nmcUrl: 'https://nmc-na12.voc.qa-integration.p-44.com/',
  tlEmissionsEnabled: true,
  portalServicesAgreementUS:
    'https://nmc-na12.voc.project44.com/resources/Documents/Legal/Portal_services_agreement_Carriers_version_18.3_US.pdf',
  portalDataProcessingAgreement:
    'https://nmc-eu12.voc.project44.com/resources/Documents/Portal_DataProcessingAgreement_Carriers_version_18.3.pdf',
  portalServicesAgreement:
    'https://nmc-eu12.voc.project44.com/resources/Documents/Portal_services_agreement_Carriers_version_18.2.pdf',
  tlAdditionalApptWindowsEnabled: true,
  isEu: false,
  tdxCarrierNetworkRolesEnabled: false,
  useOnboardingV2: true,
};
